### ISSUE TITLE
Question: Support for lygia.xyz ?

### ISSUE THREAD

**Issue by gmlewis** [JMBeresford/webgpu-kit#44]
Have you considered support for or cooperation with https://lygia.xyz/ ?
It looks like they are working on WGSL support as well, so there might be some opportunity for collaboration.

**Comment by JMBeresford** [comment]
@gmlewis As a fan and user of Lygia myself, I'm certainly open to either support and/or cooperation where applicable. I am curious about your definition of support, however. Is there a reason that existing Lygia `.wgsl` shaders would not work with the webgpu-kit api?

I would assume that one could plug and play their shader code with a webgpu-kit pipeline so long as one is cautious around name collisions. If there is a specific method of support that is currently not feasible I would certainly be open to working towards that goal, if possible.

**Comment by gmlewis** [comment]
Thank you, @JMBeresford !  I'm happy to hear that you are already a fan and user of Lygia.
By "support" I was hoping to simply reduce the amount of effort required in this webgpu-kit... possibly by making the Lygia functions automatically included.

Anyway, feel free to close this issue since it is already on your radar. I honestly don't know at this point what "support" would end up looking like. 

Thanks again for a very cool project!

**Comment by JMBeresford** [comment]
I see, I believe that something like first-class support of lygia within webgpu-kit is out of scope for this project. The goal of webgpu-kit is to minimize webgpu boilerplate while imposing as few opinions on how you use it as possible.

However, webgpu-kit is far from mature and everything and anything is subject to change!

For now, the ability to compose a shader using lygia _alongside_ webgpu should be fairly straightforward. See [this example](https://codesandbox.io/p/devbox/wgpu-kit-cube-forked-ff5wc6) and the relevant import in 'shaders.wgsl'.

---
I will close this for now, but feel free to reach out w/ any more questions or suggestions you have 😃
